# -*- coding: utf-8 -*-
"""shape-E.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4QrOuUx9mKBRCKcWq0KtX-gnATMuKJ2
"""

!pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/openai/shap-e.git
# %cd shap-e
!pip install -e .

import shap_e
print("Shap-E installed correctly")

import torch
from shap_e.diffusion.sample import sample_latents
from shap_e.diffusion.gaussian_diffusion import diffusion_from_config
from shap_e.models.download import load_model, load_config
from shap_e.util.notebooks import decode_latent_mesh

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

xm = load_model('transmitter', device=device)
model = load_model('image300M', device=device)
diffusion = diffusion_from_config(load_config('diffusion'))

print("Model ready")

from google.colab import files
uploaded = files.upload()

from PIL import Image
import os

for f in uploaded:
    os.rename(f, "input.png")

image = Image.open("input.png").convert("RGB")
image

latents = sample_latents(
    batch_size=1,
    model=model,
    diffusion=diffusion,
    guidance_scale=3.0,
    model_kwargs=dict(images=[image]),
    progress=True,
    device=device,

    # Required new arguments
    clip_denoised=True,
    use_fp16=torch.cuda.is_available(),
    use_karras=True,
    karras_steps=64,
    sigma_min=1e-3,
    sigma_max=160,
    s_churn=0.0,
)

import trimesh
mesh = decode_latent_mesh(xm, latents[0])
print("Mesh decoded")

# Convert Shap-E mesh to trimesh
vertices = mesh.verts.detach().cpu().numpy()
faces = mesh.faces.detach().cpu().numpy()

tm = trimesh.Trimesh(vertices=vertices, faces=faces)

tm.export("generated_model.obj")

print("Mesh saved as generated_model.obj")

from google.colab import files
files.download("generated_model.obj")

!git init
!git config --global user.email "selvamithra05@gmail.com"
!git config --global user.name "Selvamithra05"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile .gitignore
# __pycache__/
# *.pyc
# *.obj
# *.ply
# *.glb
# generated_views/
# shap-e/
#

!git add .
!git commit -m "Initial 2D to 3D pipeline using Shap-E"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

# Commented out IPython magic to ensure Python compatibility.
!mkdir 2d_3d_furniture_converter
# %cd 2d_3d_furniture_converter

!find /content -name "*.ipynb"

